  apiVersion: skaffold/v2beta9
  kind: Config
  deploy:
    kubectl:
      manifests:
        - ./infra/k8s/*
  build:
    local:
      push: false
    artifacts:
      - image: limardialdian/ticket-auth
        context: auth
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: limardialdian/client
        context: client
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: '**/*.ts'
              dest: .
      - image: limardialdian/tickets
        context: tickets
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: limardialdian/orders
        context: orders
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: limardialdian/expiration
        context: expiration
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: limardialdian/payments
        context: payments
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .